### ISSUE TITLE
search error

### ISSUE THREAD

**Issue by happypeter** [happypeter/happycasts#300]
```
Started GET "/search?q=cron" for 121.22.218.113 at 2015-01-20 20:56:10 -0500
Processing by PageController#search as HTML
  Parameters: {"q"=>"cron"}
Completed 500 Internal Server Error in 787ms

RuntimeError ({:message=>"500 Internal Server Error"}):
  app/controllers/page_controller.rb:15:in `search'
```

**Comment by billie66** [comment]
>Faraday::ConnectionFailed (Connection refused - connect(2) for "api.tinysou.com" port 80):
  app/controllers/page_controller.rb:15:in `search'

**Comment by billie66** [comment]
这个问题已经在 #296 中提出了，当时又数据重新导出一遍，搜索就工作了。

看来还是用 lunr.js 吧
